name: currency_textfield_example
description: Demonstrates how to use the currency_textfield plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  currency_textfield:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true