name: currency_textfield_2
description: A Controller for currency text input.
version: 2.5.0
homepage: https://github.com/Macacoazul01/currency_textfield
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
