name: currency_textfield_2
description: A Controller for currency text input.
version: 2.5.1
homepage: https://github.com/Macacoazul01/currency_textfield
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  decimal: 2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
flutter:
