name: currency_textfield
description: A flutter package that implements a Controller for currency text input.
version: 2.8.0
homepage: https://github.com/IsaiasSantana/currency_textfield
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
flutter:
